// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQuuuhIqpjl8YH8OWCWSk4ZrFJ0RWRwdc',
    appId: '1:1066497327418:web:e51f5abab7f541e8c79003',
    messagingSenderId: '1066497327418',
    projectId: 'ledgerly-5b939',
    authDomain: 'ledgerly-5b939.firebaseapp.com',
    storageBucket: 'ledgerly-5b939.firebasestorage.app',
    measurementId: 'G-HGVJYTYGHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8bEAWvUywAcZyOPw9NgFDmSCh0Nk45o',
    appId: '1:1066497327418:android:113e10b106b58218c79003',
    messagingSenderId: '1066497327418',
    projectId: 'ledgerly-5b939',
    storageBucket: 'ledgerly-5b939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJuiPGrGQA4-Ld-Y8UFzZEhAqrTuP4toY',
    appId: '1:1066497327418:ios:4d1e7ea614a2136ec79003',
    messagingSenderId: '1066497327418',
    projectId: 'ledgerly-5b939',
    storageBucket: 'ledgerly-5b939.firebasestorage.app',
    iosBundleId: 'com.example.ledgerly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJuiPGrGQA4-Ld-Y8UFzZEhAqrTuP4toY',
    appId: '1:1066497327418:ios:4d1e7ea614a2136ec79003',
    messagingSenderId: '1066497327418',
    projectId: 'ledgerly-5b939',
    storageBucket: 'ledgerly-5b939.firebasestorage.app',
    iosBundleId: 'com.example.ledgerly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQuuuhIqpjl8YH8OWCWSk4ZrFJ0RWRwdc',
    appId: '1:1066497327418:web:fee7603095f792ccc79003',
    messagingSenderId: '1066497327418',
    projectId: 'ledgerly-5b939',
    authDomain: 'ledgerly-5b939.firebaseapp.com',
    storageBucket: 'ledgerly-5b939.firebasestorage.app',
    measurementId: 'G-FXJL6R3LT1',
  );
}
